website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from website._init_ import db
from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email =request.form.get("email")
        password =request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password,password):
                flash("Logged in!")
                login_user(user,remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Password is incorrect', category='error')
        else:
            flash('Email does not exist', category='error')

    return render_template("login.html", user=current_user)

@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email =request.form.get("email")
        username =request.form.get("username")
        password1 =request.form.get("password1")
        password2 =request.form.get("password2")

        email_exists=User.query.filter_by(email=email).first()
        username_exists=User.query.filter_by(username=username).first()

        if email_exists:
            flash('Email is already in use', category='error')
        elif username_exists:
            flash('Username is already in use', category='error')
        elif password1 != password2:
            flash('Password don\'t match!', category='error')
        elif len(username) < 2:
            flash("Username is too short", category='error')
        elif len(password1) < 6:
            flash("Password is too short", category='error')
        elif len(email) < 4:
            flash("Email is too short", category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('User created!')
            return redirect(url_for('views.home'))

    return render_template("signup.html",user=current_user)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))

website/views.py
from flask import Blueprint,render_template, request, flash, redirect, url_for, abort
from flask_login import login_required,current_user
from .models import Post, User, Comment
from website._init_ import db
from website import comm
from website.forms import CommunityForm


views = Blueprint("views", __name__)

@views.route("/")
@views.route("/home")
@login_required
def home():
    posts = Post.query.all()
    return render_template ("home.html", user=current_user, posts=posts)

@views.route("/community/<string:name>")
def community(name):
    """
    Route for page displaying a community and its posts sorted by date created.
    """
    page = int(request.args.get("page", 1))
    community = comm.get_community(name)
    if community:
        posts = comm.get_community_posts(community.id, page, False)
        community_member = None
        if current_user.is_authenticated:
            community_member = comm.get_community_member(
                community.id, current_user.id
            )
        return render_template(
            "community.html",
            tab="recent",
            community=community,
            posts=posts,
            community_member=community_member,
        )
    else:
        abort(404)

@views.route("/community/<string:name>/top")
def top_community(name):
    """
    Route for page displaying a community and its posts sorted by number of upvotes.
    """
    page = int(request.args.get("page", 1))
    community = comm.get_community(name)
    if community:
        posts = comm.get_community_posts(community.id, page, True)
        community_member = None
        if current_user.is_authenticated:
            community_member = comm.get_community_member(
                community.id, current_user.id
            )
        return render_template(
            "community.html",
            tab="top",
            community=community,
            posts=posts,
            community_member=community_member,
        )
    else:
        abort(404)

@views.route("/community/create", methods=["GET", "POST"])
@login_required
def create_community():
    """
    Route for creating a community. On a GET request, it returns the community creation
    form. On a POST request, it processes a community creation.
    """
    form = CommunityForm()
    if form.validate_on_submit():
        comm.create_community(
            form.name.data, form.description.data, current_user
        )
        flash("Successfully created community.", "primary")
        return redirect(url_for("community.community", name=form.name.data))
    return render_template("create_community.html", form=form)

@views.route("/createpost", methods=['GET','POST'])
@login_required
def create_post():
    if request.method == "POST":
        text = request.form.get('text')

        if not text:
            flash('Post cannot be empty', category='error')
        else:
            post = Post(text=text, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('Post created!', category='success')
            return redirect(url_for('views.home'))

    return render_template('createpost.html', user=current_user)

@views.route("/delete-post/<id>")
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()

    if not post:
        flash("Post does not exist.", category='error')
    elif current_user.id != post.author:
        flash('You do not have permission to delete this post', category='error')
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted', category='success')

    comment = Comment.query.filter(Comment.post_id == id).all()
    if not comment:
        pass
    else:
        for c in comment:
            db.session.delete(c)
        db.session.commit()


    return redirect(url_for('views.home'))

@views.route("/posts/<username>")
@login_required
def posts(username):
    user = User.query.filter_by(username=username).first()

    if not user:
        flash('No user with that username exists', category='error')
        return redirect(url_for('views.home'))

    posts = user.posts
    return render_template("posts.html", user=current_user, posts=posts, username=username)

@views.route("/create-comment/<post_id>", methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')

    if not text:
        flash('Comment cannot be empty', category='error')
    else:
        post = Post.query.filter_by(id=post_id)
        if post:
            comment = Comment(text=text, author=current_user.id, post_id=post_id)
            db.session.add(comment)
            db.session.commit()
        else:
            flash('Post does not exist', category='error')

    return redirect(url_for('views.home'))

@views.route("/delete-comment/<comment_id>")
@login_required
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id=comment_id).first()

    if not comment:
        flash('Comment does not exist', category='error')
    elif current_user.id != comment.author and current_user.id != comment.post.author:
        flash('You do not have permission to delete this comment', category='error')
    else:
        db.session.delete(comment)
        db.session.commit()

    return redirect(url_for('views.home'))

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script src="https://kit.fontawesome.com/13066d1d8f.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="/home">Home</a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="/logout">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="/login">Login</a>
            <a class="nav-item nav-link" href="/sign-up">Sign Up</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        {% for category, message in messages %}
        {% if category == "error" %}
          <div class="alert alert-danger alter-dismissible fade show" role="alert">
          {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          </div>
        {% else %}
        <div class="alert alert-success alter-dismissible fade show" role="alert">
          {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          </div>
        {% endif %}

        {% endfor %}
      {% endif %}
    {% endwith %}
    <div class="container">{% block content %}{% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/community.html
{% extends "layout.html" %} {% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    {% if tab == "recent" %}
    <li class="breadcrumb-item active" aria-current="page">Recent</li>
    <li class="breadcrumb-item">
      <a href="{{ url_for('community.top_community', name=community.name) }}"
        >Top</a
      >
    </li>
    {% elif tab == "top" %}
    <li class="breadcrumb-item">
      <a href="{{ url_for('community.community', name=community.name) }}"
        >Recent</a
      >
    </li>
    <li class="breadcrumb-item active" aria-current="page">Top</li>
    {% endif %}
  </ol>
</nav>
<h2 class="mb-3">f/{{ community.name }}</h2>
<div class="row">
  <div class="col-8">
    {% for post in posts.items %}
    <div class="card mb-2">
      <div class="row">
        <div class="col-2">
          <ul class="list-group text-center border-0">
            <li class="list-group-item py-1 border-0">
              <form
                action="{{ url_for('post.upvote_post', name=community.name, title=post.title) }}"
                method="POST"
              >
                <small
                  ><input
                    class="border-0"
                    type="submit"
                    value="▲"
                    {%
                    if
                    not
                    current_user.is_authenticated
                    %}disabled{%
                    endif
                    %}
                /></small>
              </form>
            </li>
            <li class="list-group-item py-1 border-0">
              <small>{{ post.votes }}</small>
            </li>
            <li class="list-group-item py-1 border-0">
              <form
                action="{{ url_for('post.downvote_post', name=community.name, title=post.title) }}"
                method="POST"
              >
                <small
                  ><input
                    class="border-0"
                    type="submit"
                    value="▼"
                    {%
                    if
                    not
                    current_user.is_authenticated
                    %}disabled{%
                    endif
                    %}
                /></small>
              </form>
            </li>
          </ul>
        </div>
        <div class="col-10">
          <div class="card-body">
            <h5 class="card-title">
              <a
                class="text-dark"
                href="{{ url_for('post.post', name=community.name, title=post.title) }}"
                >{{ post.title }}</a
              >
            </h5>
            <h6 class="card-subtitle text-muted">
              <small
                >Posted on {{ post.date_created.strftime("%m/%d/%Y") }} by
                <a
                  class="text-muted"
                  href="{{ url_for('user.app_user', username=post.username) }}"
                  >u/{{ post.username }}</a
                ></small
              >
            </h6>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <nav class="my-2" aria-label="Page navigation example">
      <ul class="pagination">
        {% if posts.prev_num %}
        <li class="page-item">
          <a class="page-link" href="?page={{ posts.prev_num }}">Previous</a>
        </li>
        {% endif %} {% if posts.next_num %}
        <li class="page-item">
          <a class="page-link" href="?page={{ posts.next_num }}">Next</a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        Community Details
      </div>
      <div class="card-body">
        <p class="card-text">
          {{ community.description }}
        </p>
        <div class="container-fluid">
          <div class="row">
            <a
              href="{{ url_for('post.create_post', name=community.name) }}"
              class="btn btn-sm btn-primary mb-1"
              >Post</a
            >
          </div>
          {% if current_user.is_authenticated and community_member != None %}
          <div class="row">
            <form
              action="{{ url_for('community.leave_community', name=community.name) }}"
              method="POST"
            >
              <button class="btn btn-sm btn-primary mb-1">
                Leave
              </button>
            </form>
          </div>
          {% elif current_user.is_authenticated %}
          <div class="row">
            <form
              action="{{ url_for('community.join_community', name=community.name) }}"
              method="POST"
            >
              <button class="btn btn-sm btn-primary mb-1">
                Join
              </button>
            </form>
          </div>
          {% endif %} {% if current_user.is_authenticated and current_user.id ==
          community.user_id %}
          <div class="row">
            <a
              href="{{ url_for('community.update_community', name=community.name) }}"
              class="btn btn-sm btn-primary mb-1"
              >Update</a
            >
          </div>
          <div class="row">
            <form
              action="{{ url_for('community.delete_community', name=community.name) }}"
              method="POST"
            >
              <button class="btn btn-sm btn-danger mb-1">
                Delete
              </button>
            </form>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/create_community.html
{% extends "layout.html" %} {% block content %}
<h2 class="mb-3">Create Community</h2>
<form action="{{ url_for('community.create_community') }}" method="POST">
  {{ form.csrf_token }}
  <div class="form-group">
    {{ form.name.label }} {% if form.name.errors %} {{
    form.name(class="form-control is-invalid") }} {% for error in
    form.name.errors %}
    <div class="invalid-feedback">
      {{ error }}
    </div>
    {% endfor %} {% else %} {{ form.name(class="form-control") }} {% endif %}
  </div>
  <div class="form-group">
    {{ form.description.label }} {{ form.description(class="form-control") }}
  </div>
  {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock %}

website/templates/createpost.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<h1 align="center">Make a Post</h1>
<form method='POST'>
    <textarea name="text" id="text" class="form-control"></textarea>
    <br />
    <div align="center">
        <button type="submit" class="btn btn-lg btn-primary">Post</button>
    </div>
</form>
<br />
<div align="center">
    <a href="/home">
        <button type="submit" class="btn btn-lg btn-secondary">Back</button></a>
</div>
{% endblock %}

website/templates/feed.html
{% extends "base.html" %} {% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    {% if tab == "recent" %}
    <li class="breadcrumb-item active" aria-current="page">Recent</li>
    <li class="breadcrumb-item">
      <a href="{{ url_for('feed.top_feed') }}">Top</a>
    </li>
    {% elif tab == "top" %}
    <li class="breadcrumb-item">
      <a href="{{ url_for('feed.feed') }}">Recent</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">Top</li>
    {% endif %}
  </ol>
</nav>
<h2 class="mb-3">My Feed</h2>
<div class="row">
  <div class="col-8">
    {% if posts and posts.items|length != 0 %} {% for post in posts.items %}
    <div class="card mb-2">
      <div class="row">
        <div class="col-2">
          <ul class="list-group text-center border-0">
            <li class="list-group-item py-1 border-0">
              <form
                action="{{ url_for('post.upvote_post', name=post.community_name, title=post.title) }}"
                method="POST"
              >
                <small
                  ><input
                    class="border-0"
                    type="submit"
                    value="▲"
                    {%
                    if
                    not
                    current_user.is_authenticated
                    %}disabled{%
                    endif
                    %}
                /></small>
              </form>
            </li>
            <li class="list-group-item py-1 border-0">
              <small>{{ post.votes }}</small>
            </li>
            <li class="list-group-item py-1 border-0">
              <form
                action="{{ url_for('post.downvote_post', name=post.community_name, title=post.title) }}"
                method="POST"
              >
                <small
                  ><input
                    class="border-0"
                    type="submit"
                    value="▼"
                    {%
                    if
                    not
                    current_user.is_authenticated
                    %}disabled{%
                    endif
                    %}
                /></small>
              </form>
            </li>
          </ul>
        </div>
        <div class="col-10">
          <div class="card-body">
            <h5 class="card-title">
              <a
                class="text-dark"
                href="{{ url_for('post.post', name=post.community_name, title=post.title) }}"
                >{{ post.title }}</a
              >
            </h5>
            <h6 class="card-subtitle text-muted">
              <small
                >Posted on {{ post.date_created.strftime("%m/%d/%Y") }} by
                <a
                  class="text-muted"
                  href="{{ url_for('user.app_user', username=post.username) }}"
                  >u/{{ post.username }}</a
                ></small
              >
            </h6>
          </div>
        </div>
      </div>
    </div>
    {% endfor %} {% else %}
    <p>
      Join <a href="{{ url_for('communities.communities') }}">communities</a> to
      add them to your feed!
    </p>
    {% endif %}
    <nav class="my-2" aria-label="Page navigation example">
      <ul class="pagination">
        {% if posts.prev_num %}
        <li class="page-item">
          <a class="page-link" href="?page={{ posts.prev_num }}">Previous</a>
        </li>
        {% endif %} {% if posts.next_num %}
        <li class="page-item">
          <a class="page-link" href="?page={{ posts.next_num }}">Next</a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        Home
      </div>
      <div class="card-body">
        <p class="card-text">
          Your personal Flaskeddit frontpage. Come here to check in with your
          favorite communities!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/home.html
{% extends "posts_div.html" %}
{% block title %}Home{% endblock %}

website/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../static/styles.css">
    <title>Reddit</title>
  </head>
  <body>
  <div class="container">
<div class="logo">
  <img src="https://logos-world.net/wp-content/uploads/2020/10/Reddit-Logo.png" alt="" />
  </div>

<div class=nav>
  <ul>
   <!--search bar-->
   <div class="wrapper">
  <div class="searchBar">
    <input id="searchQueryInput" type="text" name="searchQueryInput" placeholder="Search" value="" />
    <button id="searchQuerySubmit" type="submit" name="searchQuerySubmit">
      <svg style="width:24px;height:24px" viewBox="0 0 24 24"><path fill="#666666" d="M9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.44,13.73L14.71,14H15.5L20.5,19L19,20.5L14,15.5V14.71L13.73,14.44C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3M9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5Z" />
      </svg>
    </button>
  </div>
</div>
<!--//search bar-->
  <button class="button1" type="button">Sign Up</button>
  <button class="button2" type="button">Log In</button>

  </ul>
  </div>
</div>
    </div>

<!--markup for boxes at the top-->
  <div class="page-wrapper">
    <div class="post-slider">
     <h1 class="slider-title">Trending Today</h1>

      <div class="post-wrapper">
      <div class="post post1">
        <img src="https://www.crazyforcrust.com/wp-content/uploads/2018/07/PBJ-recipe-twists-7-640x1041.jpg" width="250" height="200">
        <p>PB&J Sandwich Recipe</p>
      </div>
      <div class="post post2">
        <img src="https://www.crazyforcrust.com/wp-content/uploads/2018/07/PBJ-recipe-twists-7-640x1041.jpg" width="250" height="200">
        <p>PB&J Sandwich Recipe</p>
      </div>
        <div class="post post3">
        <img src="https://www.crazyforcrust.com/wp-content/uploads/2018/07/PBJ-recipe-twists-7-640x1041.jpg" width="250" height="200">
        <p>PB&J Sandwich Recipe</p>
      </div>
      <div class="post post4">
        <img src="https://www.crazyforcrust.com/wp-content/uploads/2018/07/PBJ-recipe-twists-7-640x1041.jpg" width="250" height="200">
        <p>PB&J Sandwich Recipe</p>
      </div>
      </div>
    </div>
  </div>
<!--//markup for boxes at the top-->

  <!--content-->
  <div class="content clearfix">
    <div class="main-content">
      <h1 class="popular-post-title">Popular Posts</h1>
    </div>
<div class="post">
  <img src="https://i.cbc.ca/1.6604598.1664829007!/fileImage/httpImage/image.JPG_gen/derivatives/16x9_780/usa-trump.JPG" alt="" class="post-image">
  <div class="post-preview">
    <h1><a href="">Donald Trump Needs You</a></h1>
    <i class="fat fa-user">Reddit user</i>
    &nbsp;
    <i class="far calender">1 hour ago</i>
    <p class="preview-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit.
    Exercitationem optio possimus a inventore maxime laborum.</p>
    <a href="" class="btn">Read more</a>
  </div>
</div>
  </div>
<!--//content-->
    <div class="content clearfix">
    <div class="main-content">
      <h1 class="popular-post-title"></h1>
    </div>
<div class="post">
  <img src="https://i.cbc.ca/1.6604598.1664829007!/fileImage/httpImage/image.JPG_gen/derivatives/16x9_780/usa-trump.JPG" alt="" class="post-image">
  <div class="post-preview">
    <h1><a href="">Donald Trump Needs You</a></h1>
    <i class="fat fa-user">Reddit user</i>
    &nbsp;
    <i class="far calender">1 hour ago</i>
    <p class="preview-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit.
    Exercitationem optio possimus a inventore maxime laborum.</p>
    <a href="" class="btn">Read more</a>
  </div>
</div>
  </div>
<!--  content-->
 <div class="content clearfix">
    <div class="main-content">
      <h1 class="popular-post-title"></h1>
    </div>
<div class="post">
  <img src="https://i.cbc.ca/1.6604598.1664829007!/fileImage/httpImage/image.JPG_gen/derivatives/16x9_780/usa-trump.JPG" alt="" class="post-image">
  <div class="post-preview">
    <h1><a href="">Donald Trump Needs You</a></h1>
    <i class="fat fa-user">Reddit user</i>
    &nbsp;
    <i class="far calender">1 hour ago</i>
    <p class="preview-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit.
    Exercitationem optio possimus a inventore maxime laborum.</p>
    <a href="" class="btn">Read more</a>
  </div>
</div>
    <div class="sidebar"></div>
  </div>
  <!--  content-->

  </body>
</html>

website/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Flaskeddit</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="icon"
      href="{{ url_for('static', filename='favicon.ico') }}"
      type="image/x-icon"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      media="screen"
      href="{{ url_for('static', filename='styles.css') }}"
    />
  </head>
  <body>
    <header class="mb-3">
      <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
        <div class="container">
          <a class="nav" href="{{ url_for('views.home') }}">
            <img
              src="{{ url_for('static', filename='logo.png') }}"
              height="30"
              alt="logo"
            />
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.home') }}">Home</a>
              </li>
              <li class="nav-item">
                <aa
                  class="nav-link"
                  href="{{ url_for('views.community') }}"
                  >Communities</aa
                >
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              {% if current_user.is_authenticated %}
                <li class="nav-item">
                  <a
                    class="nav-link btn btn-outline-primary text-primary m-1"
                    href="{{ url_for('user.app_user', username=current_user.username) }}"
                    >User</a
                  >
                </li>
                <li class="nav-item">
                  <form action="{{ url_for('auth.logout') }}" method="POST">
                    <button
                      class="nav-link btn btn-outline-primary text-primary m-1"
                    >
                      Log Out
                    </button>
                  </form>
                </li>
              {% else %}
                <li class="nav-item">
                  <a
                    class="nav-link btn btn-outline-primary text-primary m-1"
                    href="{{ url_for('auth.register') }}"
                    >Register</a
                  >
                </li>
                <li class="nav-item">
                  <a
                    class="nav-link btn btn-outline-primary text-primary m-1"
                    href="{{ url_for('auth.login') }}"
                    >Log In</a
                  >
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <section class="full-height">
      <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% for category, message in messages %}
            <div
              class="alert alert-{{ category }} alert-dismissible fade show"
              role="alert"
            >
              {{ message }}
              <button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endwith %}
        {% block content %} {% endblock %}
      </div>
    </section>
    <footer class="bg-light">
      <div class="container">
        <div class="row fifth-height">
          <div class="col-12 align-self-center text-center">
            <p>
              Made with <span class="text-danger">&#9829;</span> by aqche.
              <a
                href="https://github.com/aqche/flaskeddit"
                target="_blank"
                class="text-dark is-link"
                ><i class="fab fa-github"></i
              ></a>
            </p>
          </div>
        </div>
      </div>
    </footer>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/posts.html
{% extends "posts_div.html" %}
{% block title %}{{username}}'s posts{% endblock %}
{% block header %}{{username}}'s posts{% endblock %}
{% block footer %}
<div align="center">
        <a href="/home">
        <button type="button" class="btn btn-primary btn-lg">Back</button>
        </a>
    </div>
{% endblock %}